version: '2'

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq-host
    image: 'rabbitmq:3.8-management'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-tier

  redis:
    container_name: redis
    hostname: redis-host
    image: 'redis:6.2.6-alpine'
    ports:
      - 6379:6379
    networks:
      - app-tier

  app:
    container_name: boot-camel
    image: 'boot-camel:0.0.1-SNAPSHOT'
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=mvn"
#user:guest
#pass:guest
    depends_on:
      - rabbitmq
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge