version: "3.8"

services:

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq-host
    image: 'rabbitmq:3.8-management'
    ports:
      - 5672:5672
      - 15672:15672

  app:
    container_name: boot-camel
    image: 'boot-camel:0.0.1-SNAPSHOT'
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=mvn"

  redis0:
    container_name: redis0
    image: mnadeem/redis
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    ports:
      - "9011:6379"
    hostname: redis0
    restart: always
    depends_on:
      - redis1
  redis1:
    container_name: redis1
    image: mnadeem/redis
    ports:
      - "9012:6379"
    hostname: redis1
    restart: always
    depends_on:
      - redis2
  redis2:
    container_name: redis2
    image: mnadeem/redis
    ports:
      - "9013:6379"
    hostname: redis2
    restart: always
    depends_on:
      - redis3
  redis3:
    container_name: redis3
    image: mnadeem/redis
    ports:
      - "9014:6379"
    hostname: redis3
    restart: always
    depends_on:
      - redis4
  redis4:
    container_name: redis4
    image: mnadeem/redis
    ports:
      - "9015:6379"
    hostname: redis4
    restart: always
    depends_on:
      - redis5
  redis5:
    container_name: redis5
    image: mnadeem/redis
    ports:
      - "9016:6379"
    hostname: redis5
    restart: always

networks:
  default:
    name: app-tier